version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ${PWD}:/app
    networks:
      my_network:
        ipv4_address: 10.11.0.11
    restart: always
  db:
    build:
      context: pg/
      dockerfile: Dockerfile.pgsql
    container_name: docker-postgre
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '25432:5432'
    networks:
      my_network:
        ipv4_address: 10.11.0.3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always
volumes:
  db:
    driver: local
networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16
    external: true
